### ISSUE TITLE
StatusCodeError: 426 - „This service requires use of the HTTPS protocol.“

### ISSUE THREAD

**Issue by nefiertsrebliS** [iobroker-community-adapters/ioBroker.worx#222]
Worx scheint den Cloud-Dienst heute auf HTTPS umgestellt zu haben. Wenn ich in der api.js in Zeile 455

`uri: ‚http://‘ + URL + PATH + path,`

durch 

`uri: ‚https://‘ + URL + PATH + path,`

ersetze, funktioniert alles wieder.

**Comment by MeisterTR** [comment]
fixed in 1.3.0

**Comment by nefiertsrebliS** [comment]
das ging schnell!
1000 Dank

**Comment by hsteinme** [comment]
@nefiertsrebliS : Für viele User wäre es sinnvoll, das Fehlersymptom in einem Issue beschrieben zu sehen. Dann wäre es für sie einfacher zu erkennen, dass die Lösung des Issues für sie relevant ist.

**Comment by nefiertsrebliS** [comment]
@hsteinme : Ich würde da gerne noch weiteres Hilfreiches zu schreiben, aber außer der Fehlermeldung 
`StatusCodeError: 426 - „This service requires use of the HTTPS protocol.“`
kommt nichts mehr. Also wenn die Fehlermeldung kommt, einfach das Update einspielen und den Dienst neu starten, dann ist alles wieder gut.

**Comment by Wilhelm08** [comment]
Danke für das Update aber jetzt habe ich aber folgede Fehler:

worx.0 | 2021-04-15 18:37:04.097 | error | (18614) ERROR: StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
-- | -- | -- | --
worx.0 | 2021-04-15 18:37:04.096 | error | (18614) Could not Connect to Worx Server: StatusCodeError: 403 - "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n</body>\r\n</html>\r\n"
worx.0 | 2021-04-15 18:37:03.890 | info | (18614) worx is selected
worx.0 | 2021-04-15 18:37:03.771 | info | (18614) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.worx, node: v12.20.1, js-controller: 3.2.16
host.raspberryiob | 2021-04-15 18:37:01.718 | info | instance system.adapter.worx.0 started with pid 18614
host.raspberryiob | 2021-04-15 18:37:00.675 | info | Restart adapter system.adapter.worx.0 because enabled
host.raspberryiob | 2021-04-15 18:37:00.674 | info | instance system.adapter.worx.0 scheduled normal terminated and will be restarted on schedule.
worx.0 | 2021-04-15 18:37:00.036 | info | (18538) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
worx.0 | 2021-04-15 18:37:00.031 | info | (18538) terminating
worx.0 | 2021-04-15 18:37:00.016 | info | (18538) cleaned everything up...

Bitte um hilfe

**Comment by Woersty** [comment]
@Wilhelm08  Du hast dich ausgesperrt wegen zu vieler Anfragen. Router neu starten (neue IP) oder 24 h warten.
