### ISSUE TITLE
Could not Connect to Worx Server: StatusCodeError: 404

### ISSUE THREAD

**Issue by marcprenger** [iobroker-community-adapters/ioBroker.worx#575]
Since today I'm getting the following error message when connecting to Worx servers:
![image](https://user-images.githubusercontent.com/27813142/193056797-9298e4ae-f4a5-4d5d-badc-4a4a041096ca.png)

Am I the only one? Is this a bug?

Happy to provide more information :)

**Comment by Assemblerguru** [comment]
I have the same problem I think since a few days...tried a second instance but the same. 

Logon the web or mobile app (android) still works,, so username and pwd are ok.

Hope, this can be fixed. Or ist it just a temp problem with servers ?

br,
A.

![WorxAdapterError](https://user-images.githubusercontent.com/20387658/193058996-ecf6c3ff-a574-4473-b19e-58439ebec26f.png)
